name: PR workflow - FEAT

on:
  pull_request:
    branches: main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hi all!"
      - uses: actions/checkout@v4.2.2
      - name: List files
        run: ls
